### ISSUE TITLE
dydra query - undefined method 'result'

### ISSUE THREAD

**Issue by cldwalker** [dydra/dydra#4]
Here's what I tried on the latest dydra on osx 10.5.8:

```
$ dydra query bookmarks 'SELECT DISTINCT ?o WHERE { ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o . }'
/Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/rdf-0.3.2/lib/rdf/query/solution.rb:201:in `method_missing': undefined method `result' for #<RDF::Query::Solution:0x1988dd8> (NoMethodError)
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.6/lib/dydra/repository.rb:237:in `parse_bindings'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.6/lib/dydra/repository.rb:215:in `query'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.6/lib/dydra/command/query.rb:27:in `execute'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.6/lib/dydra/command.rb:81:in `wrap_errors'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.6/lib/dydra/command.rb:61:in `catch_errors'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.6/lib/dydra/command.rb:80:in `wrap_errors'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.6/bin/dydra:136:in `query'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.6/bin/dydra:64:in `send'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.6/bin/dydra:64:in `run_command'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.6/bin/dydra:59:in `initialize'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.6/bin/dydra:162:in `new'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.6/bin/dydra:162
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/bin/dydra:19:in `load'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/bin/dydra:19
```

Seems the faulty code in question is `bindings.first.result.respond_to?(:object)`. Adding an additional `bindings.first.respond_to?(:result)` in that if statement would prevent this. I would pull request but it's hard to tell what the intended behavior is without tests.

**Comment by bhuga** [comment]
You're correct that it's hard to see what's going on without tests, especially considering we changed the format for parsed results to one that is much, much, much less verbose. This was a bug that only affected select queries with result sizes of 1, and the just-pushed 0.0.7 successful executes the given query. Thanks for reporting this.

**Comment by cldwalker** [comment]
Thanks for fixing.
