### ISSUE TITLE
query with no matching bindings causes exception

### ISSUE THREAD

**Issue by cldwalker** [dydra/dydra#5]
So I accidently made this invalid sparql query on OSX 10.5.8 and ruby 1.8.7:

```
$ dydra query bookmarks 'select distinct ?p where { ?s <http://www.holygoat.co.uk/owl/redwood/0.1/tags/taggedOn> ?o }'
/Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/lib/dydra/repository.rb:247:in `parse_json_value': undefined method `to_sym' for nil:NilClass (NoMethodError)
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/lib/dydra/repository.rb:232:in `parse_bindings'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/lib/dydra/repository.rb:230:in `each_with_index'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/lib/dydra/repository.rb:231:in `each'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/lib/dydra/repository.rb:231:in `each_with_index'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/lib/dydra/repository.rb:231:in `parse_bindings'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/lib/dydra/repository.rb:229:in `map'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/lib/dydra/repository.rb:229:in `parse_bindings'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/lib/dydra/repository.rb:215:in `query'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/lib/dydra/command/query.rb:27:in `execute'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/lib/dydra/command.rb:81:in `wrap_errors'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/lib/dydra/command.rb:61:in `catch_errors'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/lib/dydra/command.rb:80:in `wrap_errors'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/bin/dydra:136:in `query'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/bin/dydra:64:in `send'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/bin/dydra:64:in `run_command'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/bin/dydra:59:in `initialize'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/bin/dydra:162:in `new'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/gems/dydra-0.0.7/bin/dydra:162
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/bin/dydra:19:in `load'
    from /Users/bozo/.rvm/gems/ruby-1.8.7-p299@blah/bin/dydra:19
```

Seems the failing is due to Repository#parse_json_value assuming it'll get a hash with type and value keys when this case actually passes it an empty hash. Verified with:

```
 $ dydra query bookmarks 'select distinct ?p where { ?s <http://www.holygoat.co.uk/owl/redwood/0.1/tags/taggedOn> ?o }' -j
 { "head": { "vars": [ "p" ] },
 "results": {
 "bindings": [
  {  } ] } }
```

**Comment by bhuga** [comment]
This is actually a Dydra bug, which we're now tracking internally. The result being returned is internally inconsistent. I'll let you know here when we have it fixed.

**Comment by bhuga** [comment]
We're considering fixing this internally, since the primary use case for a successful query having no bounded variables is, as far as i can tell, a typo in a variable name. Decisions, decisions.

In the meantime, a fix is in HEAD.
